[project]
name = "qemu-cli"
version = "0.1.0"
description = "QEMU QMP based CLI"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "aiofiles>=24.1.0",
    "click>=8.2.1",
    "pyyaml>=6.0.2",
    "qemu-qmp>=0.0.3",
]
